// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cmd.proto

package tech;

public final class CmdSerializable {
  private CmdSerializable() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CmdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string IMEI = 1;
    boolean hasIMEI();
    String getIMEI();
    
    // required string Cmd = 2;
    boolean hasCmd();
    String getCmd();
    
    // required string MsgId = 3;
    boolean hasMsgId();
    String getMsgId();
    
    // required string Ts = 4;
    boolean hasTs();
    String getTs();
    
    // required .Value Value = 5;
    boolean hasValue();
    Value getValue();
    ValueOrBuilder getValueOrBuilder();
  }
  public static final class Cmd extends
      com.google.protobuf.GeneratedMessage
      implements CmdOrBuilder {
    // Use Cmd.newBuilder() to construct.
    private Cmd(Builder builder) {
      super(builder);
    }
    private Cmd(boolean noInit) {}
    
    private static final Cmd defaultInstance;
    public static Cmd getDefaultInstance() {
      return defaultInstance;
    }
    
    public Cmd getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CmdSerializable.internal_static_Cmd_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CmdSerializable.internal_static_Cmd_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string IMEI = 1;
    public static final int IMEI_FIELD_NUMBER = 1;
    private Object iMEI_;
    public boolean hasIMEI() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getIMEI() {
      Object ref = iMEI_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          iMEI_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIMEIBytes() {
      Object ref = iMEI_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        iMEI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Cmd = 2;
    public static final int CMD_FIELD_NUMBER = 2;
    private Object cmd_;
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getCmd() {
      Object ref = cmd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          cmd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCmdBytes() {
      Object ref = cmd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string MsgId = 3;
    public static final int MSGID_FIELD_NUMBER = 3;
    private Object msgId_;
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getMsgId() {
      Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msgId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string Ts = 4;
    public static final int TS_FIELD_NUMBER = 4;
    private Object ts_;
    public boolean hasTs() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getTs() {
      Object ref = ts_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ts_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTsBytes() {
      Object ref = ts_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ts_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .Value Value = 5;
    public static final int VALUE_FIELD_NUMBER = 5;
    private Value value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public Value getValue() {
      return value_;
    }
    public ValueOrBuilder getValueOrBuilder() {
      return value_;
    }
    
    private void initFields() {
      iMEI_ = "";
      cmd_ = "";
      msgId_ = "";
      ts_ = "";
      value_ = Value.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasIMEI()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getValue().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIMEIBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCmdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTsBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, value_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIMEIBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCmdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTsBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Cmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Cmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Cmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Cmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Cmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Cmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Cmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Cmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Cmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Cmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Cmd prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CmdSerializable.internal_static_Cmd_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CmdSerializable.internal_static_Cmd_fieldAccessorTable;
      }
      
      // Construct using tech.CmdSerializable.Cmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getValueFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        iMEI_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ts_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (valueBuilder_ == null) {
          value_ = Value.getDefaultInstance();
        } else {
          valueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cmd.getDescriptor();
      }
      
      public Cmd getDefaultInstanceForType() {
        return Cmd.getDefaultInstance();
      }
      
      public Cmd build() {
        Cmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Cmd buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Cmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Cmd buildPartial() {
        Cmd result = new Cmd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iMEI_ = iMEI_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (valueBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = valueBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Cmd) {
          return mergeFrom((Cmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Cmd other) {
        if (other == Cmd.getDefaultInstance()) return this;
        if (other.hasIMEI()) {
          setIMEI(other.getIMEI());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasIMEI()) {
          
          return false;
        }
        if (!hasCmd()) {
          
          return false;
        }
        if (!hasMsgId()) {
          
          return false;
        }
        if (!hasTs()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        if (!getValue().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              iMEI_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              cmd_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              msgId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              ts_ = input.readBytes();
              break;
            }
            case 42: {
              Value.Builder subBuilder = Value.newBuilder();
              if (hasValue()) {
                subBuilder.mergeFrom(getValue());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setValue(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string IMEI = 1;
      private Object iMEI_ = "";
      public boolean hasIMEI() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getIMEI() {
        Object ref = iMEI_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          iMEI_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIMEI(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        iMEI_ = value;
        onChanged();
        return this;
      }
      public Builder clearIMEI() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iMEI_ = getDefaultInstance().getIMEI();
        onChanged();
        return this;
      }
      void setIMEI(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        iMEI_ = value;
        onChanged();
      }
      
      // required string Cmd = 2;
      private Object cmd_ = "";
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getCmd() {
        Object ref = cmd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCmd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cmd_ = value;
        onChanged();
        return this;
      }
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      void setCmd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        cmd_ = value;
        onChanged();
      }
      
      // required string MsgId = 3;
      private Object msgId_ = "";
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getMsgId() {
        Object ref = msgId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsgId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msgId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      void setMsgId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        msgId_ = value;
        onChanged();
      }
      
      // required string Ts = 4;
      private Object ts_ = "";
      public boolean hasTs() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getTs() {
        Object ref = ts_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ts_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTs(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ts_ = value;
        onChanged();
        return this;
      }
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ts_ = getDefaultInstance().getTs();
        onChanged();
        return this;
      }
      void setTs(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        ts_ = value;
        onChanged();
      }
      
      // required .Value Value = 5;
      private Value value_ = Value.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Value, Value.Builder, ValueOrBuilder> valueBuilder_;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public Value getValue() {
        if (valueBuilder_ == null) {
          return value_;
        } else {
          return valueBuilder_.getMessage();
        }
      }
      public Builder setValue(Value value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          valueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setValue(
          Value.Builder builderForValue) {
        if (valueBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          valueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeValue(Value value) {
        if (valueBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              value_ != Value.getDefaultInstance()) {
            value_ =
              Value.newBuilder(value_).mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          valueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearValue() {
        if (valueBuilder_ == null) {
          value_ = Value.getDefaultInstance();
          onChanged();
        } else {
          valueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public Value.Builder getValueBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getValueFieldBuilder().getBuilder();
      }
      public ValueOrBuilder getValueOrBuilder() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilder();
        } else {
          return value_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Value, Value.Builder, ValueOrBuilder>
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Value, Value.Builder, ValueOrBuilder>(
                  value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Cmd)
    }
    
    static {
      defaultInstance = new Cmd(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Cmd)
  }
  
  public interface ValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string Channel = 1;
    boolean hasChannel();
    String getChannel();
    
    // required string OrderNo = 2;
    boolean hasOrderNo();
    String getOrderNo();
  }
  public static final class Value extends
      com.google.protobuf.GeneratedMessage
      implements ValueOrBuilder {
    // Use Value.newBuilder() to construct.
    private Value(Builder builder) {
      super(builder);
    }
    private Value(boolean noInit) {}
    
    private static final Value defaultInstance;
    public static Value getDefaultInstance() {
      return defaultInstance;
    }
    
    public Value getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CmdSerializable.internal_static_Value_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CmdSerializable.internal_static_Value_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string Channel = 1;
    public static final int CHANNEL_FIELD_NUMBER = 1;
    private Object channel_;
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getChannel() {
      Object ref = channel_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          channel_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getChannelBytes() {
      Object ref = channel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string OrderNo = 2;
    public static final int ORDERNO_FIELD_NUMBER = 2;
    private Object orderNo_;
    public boolean hasOrderNo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getOrderNo() {
      Object ref = orderNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          orderNo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOrderNoBytes() {
      Object ref = orderNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        orderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      channel_ = "";
      orderNo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasChannel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrderNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getChannelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOrderNoBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getChannelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOrderNoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Value parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Value parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Value parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Value parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Value parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Value parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Value parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Value parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Value parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Value parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Value prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CmdSerializable.internal_static_Value_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CmdSerializable.internal_static_Value_fieldAccessorTable;
      }
      
      // Construct using tech.CmdSerializable.Value.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        channel_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        orderNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Value.getDescriptor();
      }
      
      public Value getDefaultInstanceForType() {
        return Value.getDefaultInstance();
      }
      
      public Value build() {
        Value result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Value buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Value result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Value buildPartial() {
        Value result = new Value(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.channel_ = channel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.orderNo_ = orderNo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Value) {
          return mergeFrom((Value)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Value other) {
        if (other == Value.getDefaultInstance()) return this;
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        if (other.hasOrderNo()) {
          setOrderNo(other.getOrderNo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasChannel()) {
          
          return false;
        }
        if (!hasOrderNo()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              channel_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              orderNo_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string Channel = 1;
      private Object channel_ = "";
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getChannel() {
        Object ref = channel_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          channel_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setChannel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        channel_ = value;
        onChanged();
        return this;
      }
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      void setChannel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        channel_ = value;
        onChanged();
      }
      
      // required string OrderNo = 2;
      private Object orderNo_ = "";
      public boolean hasOrderNo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getOrderNo() {
        Object ref = orderNo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          orderNo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOrderNo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        orderNo_ = value;
        onChanged();
        return this;
      }
      public Builder clearOrderNo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        orderNo_ = getDefaultInstance().getOrderNo();
        onChanged();
        return this;
      }
      void setOrderNo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        orderNo_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Value)
    }
    
    static {
      defaultInstance = new Value(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Value)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Cmd_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Cmd_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Value_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Value_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tCmd.proto\"R\n\003Cmd\022\014\n\004IMEI\030\001 \002(\t\022\013\n\003Cmd\030" +
      "\002 \002(\t\022\r\n\005MsgId\030\003 \002(\t\022\n\n\002Ts\030\004 \002(\t\022\025\n\005Valu" +
      "e\030\005 \002(\0132\006.Value\")\n\005Value\022\017\n\007Channel\030\001 \002(" +
      "\t\022\017\n\007OrderNo\030\002 \002(\tB\027\n\004techB\017CmdSerializa" +
      "ble"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Cmd_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Cmd_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Cmd_descriptor,
              new String[] { "IMEI", "Cmd", "MsgId", "Ts", "Value", },
              Cmd.class,
              Cmd.Builder.class);
          internal_static_Value_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Value_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Value_descriptor,
              new String[] { "Channel", "OrderNo", },
              Value.class,
              Value.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
